const { MeiliSearch } = require("meilisearch");

const products = [
  {
    id: 116939,
    barcode: null,
    product_name: "hypo toilet cleaner",
    alias: "hypo toilet cleaner",
    slug: "hypo-toilet-cleaner-11",
    category_id: 113,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 2499,
    contributor_type: "manager",
    contributor_store_id: 1756,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2021-12-31 14:52:21",
    updated_at: "2021-12-31 14:52:21",
  },
  {
    id: 122020,
    barcode: null,
    product_name: "hypo toilet cleaner",
    alias: "hypo toilet cleaner",
    slug: "hypo-toilet-cleaner-13",
    category_id: 55,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 2830,
    contributor_type: "merchant",
    contributor_store_id: 1927,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-01-08 09:27:41",
    updated_at: "2022-01-08 09:27:41",
  },
  {
    id: 136864,
    barcode: null,
    product_name: "hypo toilet cleaner",
    alias: "hypo toilet cleaner",
    slug: "hypo-toilet-cleaner-14",
    category_id: 181,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 2731,
    contributor_type: "merchant",
    contributor_store_id: 1876,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-02-02 10:44:17",
    updated_at: "2022-02-02 10:44:17",
  },
  {
    id: 147856,
    barcode: null,
    product_name: "hypo toilet cleaner",
    alias: "hypo toilet cleaner",
    slug: "hypo-toilet-cleaner-15",
    category_id: 150,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 3228,
    contributor_type: "manager",
    contributor_store_id: 1517,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-02-20 13:05:05",
    updated_at: "2022-02-20 13:05:05",
  },
  {
    id: 149929,
    barcode: null,
    product_name: "Hypo toilet cleaner",
    alias: "Hypo toilet cleaner",
    slug: "hypo-toilet-cleaner-16",
    category_id: 181,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 904,
    contributor_type: "merchant",
    contributor_store_id: 2104,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-02-22 16:17:18",
    updated_at: "2022-02-22 16:17:18",
  },
  {
    id: 166945,
    barcode: null,
    product_name: "Hypo Toilet Cleaner",
    alias: "Hypo Toilet Cleaner",
    slug: "hypo-toilet-cleaner-19",
    category_id: 113,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 2765,
    contributor_type: "merchant",
    contributor_store_id: 1891,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-03-18 17:16:00",
    updated_at: "2022-03-18 17:16:00",
  },
  {
    id: 201147,
    barcode: null,
    product_name: "Hypo Toilet Cleaner",
    alias: "Hypo Toilet Cleaner",
    slug: "hypo-toilet-cleaner-24",
    category_id: 55,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 2924,
    contributor_type: "manager",
    contributor_store_id: 1575,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-05-11 11:18:56",
    updated_at: "2022-05-11 11:18:56",
  },
  {
    id: 211064,
    barcode: null,
    product_name: "hypo toilet cleaner",
    alias: "hypo toilet cleaner",
    slug: "hypo-toilet-cleaner-25",
    category_id: 57,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 4125,
    contributor_type: "manager",
    contributor_store_id: 2523,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-05-27 12:39:36",
    updated_at: "2022-05-27 12:39:36",
  },
  {
    id: 283607,
    barcode: null,
    product_name: "Hypo Toilet Cleaner",
    alias: "Hypo Toilet Cleaner",
    slug: "hypo-toilet-cleaner-27",
    category_id: 150,
    size: "450ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 5557,
    contributor_type: "manager",
    contributor_store_id: 3031,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-08-13 16:37:46",
    updated_at: "2022-08-13 16:37:46",
  },
  {
    id: 49915,
    barcode: null,
    product_name: "NEFIXIME SUSPENSION 100mg/5ml",
    alias: "NEFIXIME SUSPENSION 100mg/5ml",
    slug: "nefixime-suspension-100mg5ml",
    category_id: 185,
    size: "60ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 1438,
    contributor_type: "manager",
    contributor_store_id: 1170,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2021-04-29 13:23:43",
    updated_at: "2021-04-29 13:23:43",
  },
  {
    id: 149369,
    barcode: null,
    product_name: "nefixime oral suspension 100mg/5ml",
    alias: "nefixime oral suspension 100mg/5ml",
    slug: "nefixime-oral-suspension-100mg5ml",
    category_id: 185,
    size: "60ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 3228,
    contributor_type: "manager",
    contributor_store_id: 1517,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-02-22 08:21:05",
    updated_at: "2022-02-22 08:21:05",
  },
  {
    id: 14336,
    barcode: null,
    product_name: "Smart collection no262 men perfume deodorant body spray",
    alias: "Smart collection no262 men perfume deodorant body spray",
    slug: "smart-collection-no262-men-perfume-deodorant-body-spray",
    category_id: 181,
    size: "200ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 94,
    contributor_type: "merchant",
    contributor_store_id: 79,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2020-08-13 09:18:09",
    updated_at: "2021-10-22 14:46:30",
  },
  {
    id: 14338,
    barcode: null,
    product_name: "Smart collection No.467 men perfume deodorant body spray",
    alias: "Smart collection No.467 men perfume deodorant body spray",
    slug: "smart-collection-no467-men-perfume-deodorant-body-spray",
    category_id: 181,
    size: "200ml",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 94,
    contributor_type: "merchant",
    contributor_store_id: 79,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2020-08-13 09:21:02",
    updated_at: "2021-10-22 14:46:30",
  },
  {
    id: 3737,
    barcode: 8690536840168,
    product_name: "Molfix Baby Diaper 2 mini 3-6kg 20pcs Comfort Fix",
    alias: "Molfix Baby Diaper 2 mini 3-6kg 20pcs Comfort Fix",
    slug: "molfix-baby-diaper-2-mini-3-6kg-20pcs-comfort-fix",
    category_id: 24,
    size: "3-6kg",
    product_type: null,
    product_thumbnail:
      "https://shopkite.s3.amazonaws.com/products/thumbnail/molfix-baby-diaper-2-mini-3-6kg-20pcs-comfort-fix.jpg",
    product_image: "20181124021701.jpg",
    manufacturer_id: 159,
    contributor_id: 8,
    contributor_type: "admin",
    contributor_store_id: null,
    product_status: "verified",
    country: "nigeria",
    reg_no: "03-1788",
    model_no: "",
    sync: 1,
    visible_online: 1,
    created_at: "2018-11-24 12:16:14",
    updated_at: "2020-03-21 17:02:15",
  },
  {
    id: 141704,
    barcode: null,
    product_name: "Molfix Baby Diaper comfort Fix Mini 3-6kg",
    alias: "Molfix Baby Diaper comfort Fix Mini 3-6kg",
    slug: "molfix-baby-diaper-comfort-fix-mini-3-6kg",
    category_id: 24,
    size: "10pcs",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 2795,
    contributor_type: "manager",
    contributor_store_id: 1908,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-02-11 15:08:42",
    updated_at: "2022-02-11 15:08:42",
  },
  {
    id: 136002,
    barcode: null,
    product_name: "Chloramphenicol eye ointment",
    alias: "Chloramphenicol eye ointment",
    slug: "chloramphenicol-eye-ointment-22",
    category_id: 55,
    size: "3.5g",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 2921,
    contributor_type: "merchant",
    contributor_store_id: 1962,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-02-01 10:31:26",
    updated_at: "2022-02-01 10:31:26",
  },
  {
    id: 255878,
    barcode: null,
    product_name: "CHLORAMPHENICOL EYE OINTMENT DR",
    alias: "CHLORAMPHENICOL EYE OINTMENT DR",
    slug: "chloramphenicol-eye-ointment-dr",
    category_id: null,
    size: "0g",
    product_type: null,
    product_thumbnail: null,
    product_image: null,
    manufacturer_id: null,
    contributor_id: 4929,
    contributor_type: "merchant",
    contributor_store_id: 3022,
    product_status: "unverified",
    country: "nigeria",
    reg_no: null,
    model_no: null,
    sync: 0,
    visible_online: 0,
    created_at: "2022-07-28 08:07:34",
    updated_at: "2022-07-28 08:07:34",
  },
  {
    id: 89337,
    barcode: null,
    product_name: "Pharmamax Amlodipine 10mg tablet",
    alias: "Pharmamax Amlodipine 10mg tablet",
    slug: "pharmamax-amlodipine-10mg-tablet",
    category_id: 199,
    size: "2x14",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 2078,
    contributor_type: "merchant",
    contributor_store_id: 1525,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2021-10-15 10:33:44",
    updated_at: "2021-10-15 10:33:44",
  },
  {
    id: 270875,
    barcode: null,
    product_name: "Amlodipine 10mg Tablet",
    alias: "Amlodipine 10mg Tablet",
    slug: "amlodipine-10mg-tablet",
    category_id: 199,
    size: "2×14",
    product_type: null,
    product_thumbnail: "",
    product_image: "",
    manufacturer_id: 2769,
    contributor_id: 4758,
    contributor_type: "merchant",
    contributor_store_id: 2921,
    product_status: "unverified",
    country: "",
    reg_no: "",
    model_no: "",
    sync: 0,
    visible_online: 0,
    created_at: "2022-08-06 15:28:08",
    updated_at: "2022-08-06 15:28:08",
  },
];

(async () => {
  const client = new MeiliSearch({
    host: "http://127.0.0.1:7700",
    // apiKey: "MASTER_KEY",
  });

  console.log("MeiliSearch Fulltext Search Demo");

  const index = client.index("products", { primaryKey: "id" });

  console.log("Populating index with demo data...");

  const response = await index.addDocuments(products);

  console.log(response);

  console.log("Searching with query `hypo toilet cleaner...`");

  const search = await index.search("hypo toilet cleaner");

  console.log("Search complete. Printing results!");
  
  console.log(search);
})();
